CAD-878: Node real launch time.
input-output-hk/cardano-benchmarking pull request #46
Opened 2020-05-06 11:55 UTC by denisshevchenko

Previously RTView calculated "Node uptime" based on start time which was a time when the first `LogObject` was received. Technically it's incorrect because we want to know when the node was really launched. Now node sends `LogObject` with its real launch time.

2020-05-06 12:06 UTC, CodiePP requested changes

2020-05-06 12:06 UTC, CodiePP commented on cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
> +  newNi = currentNi { niStartTime = read (T.unpack startTime) :: UTCTime }
should not need to be translated from a text!
can't you trace the start time as a numeric value? something like nanoseconds?

2020-05-06 21:28 UTC, CodiePP requested changes
based on Nanoseconds

2020-05-06 21:28 UTC, CodiePP commented on cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
> +                LogValue "upTime" (PureD upTimeInSec) ->
```suggestion
                LogValue "upTime" (Nanoseconds upTimeInNanosecs) ->
```

2020-05-06 21:28 UTC, CodiePP commented on cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
> +                  nodesStateWith $ updateNodeUpTime ns upTimeInSec
```suggestion
                  nodesStateWith $ updateNodeUpTime ns upTimeInNanosecs
```

2020-05-07 05:44 UTC, denisshevchenko commented
@CodiePP Fixed.

2020-05-07 08:56 UTC, CodiePP approved these changes
OK, looks nice. Just a single last comment.

2020-05-07 08:56 UTC, CodiePP commented on cardano-rt-view/src/Cardano/Benchmarking/RTView/NodeState/Updater.hs
> +  -- now <- liftIO getCurrentTime
```suggestion

```
seems not to be used anywhere

2020-05-07 11:15 UTC, CodiePP commented
bors r+

2020-05-07 11:40 UTC, merged